name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # The folder to publish (root directory in this case)
          publish_branch: gh-pages # The branch to deploy to
          force_orphan: true # Use this option to create a clean deployment
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
